openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API yiee
  contact:
    email: ralamosm@wearehackerone.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
paths:
  /inventory:
    get:
      summary: searches inventory
      description: |
        By passing in the appropriate options, you can search foro
        available inventory in the systemo
      responses:
        "200":
          description: taken from a url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ultroncycledddfffyolo'
        "400":
          description: bad input parameter
components:
  schemas:
    ultroncycledddfffyolo:
      type: object
