openapi: 3.0.0
info:
  title: AWS Metadata API
  description: "Internal API to expose AWS metadata for retrieving access key ID,\
    \ secret key ID, and more."
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/test-ralamosm-org-1/test-simple-api/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /metadata:
    get:
      summary: Retrieve AWS Metadata
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              examples:
                example1:
                  $ref: '#/components/examples/lol'
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        AccessKeyId:
          type: string
        SecretAccessKey:
          type: string
        Token:
          type: string
        Expiration:
          type: string
          format: date-time
        Code:
          type: string
        LastUpdated:
          type: string
          format: date-time
        Type:
          type: string
  examples:
    lol: {}
