openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API yiee
  contact:
    email: ralamosm@wearehackerone.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
paths:
  /inventory:
    get:
      summary: searches inventory
      description: |
        By passing in the appropriate options, you can search foro
        available inventory in the systemtamll
      responses:
        "200":
          description: search results matching criteriaaaam
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: bad input parameter
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        foo:
          type: string
          format: uri
          example: "{$ref=https://confianze.io/ultronoezi/small.yaml}"
  responses:
    loljskk:
      description: search results matching criteriaaaam
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_200'
